// bed_pipeline_test.cpp — PR-2 end-to-end regression test.
//
// Pipeline:
//   BedReaderPool (pread)  →  decode_marker (MAF + QC + re-pack)  →  PackedFlat
//
// Reference: use the per-marker debug lines already written by saige-null in
//   benchmark_results/ukb_ldl/cpp_covT*/stdout.log
//
// lines of the form:
//   Marker 0: freq=0.0364204, maf=0.0364204, missRate=0.0437045, passQC=1
// generated by SAIGE_step1_fast.cpp:942 during the production run. Parsing
// them gives us ground truth for the first 20 markers without touching the
// live binary.
//
// Sample membership:
//   We reproduce the sample-subset logic from main.cpp:
//     - read the pheno TSV (eid column)
//     - read the mapped FAM (IID column)
//     - build indicatorGenoSamplesWithPheno[0..N-1]  (true iff FAM row's IID
//       is present in the pheno file)
//     - build ptrsubSampleInGeno in *ascending FAM-row order* (matches the
//       FAM-ordering fix applied earlier this session)
//
// Usage:
//   ./bed_pipeline_test <bed> <fam> <pheno.tsv> <pheno_iid_col> \
//                       <stdout.log> [n_markers=20] [minMAF=0.01] [maxMiss=0.15]
//
// Exit code 0 on byte-level match across all compared markers; 1 otherwise.

#include "bed_reader.hpp"
#include "marker_decoder.hpp"
#include "packed_store.hpp"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <regex>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

namespace {

struct RefLine {
  int   marker;
  float freq;
  float maf;
  float missRate;
  bool  passQC;
};

// split on delimiter (chosen at runtime based on the header line)
std::vector<std::string> split_delim(const std::string& s, char delim) {
  std::vector<std::string> out;
  std::string cur;
  for (char c : s) {
    if (c == delim) { out.push_back(cur); cur.clear(); }
    else cur.push_back(c);
  }
  out.push_back(cur);
  return out;
}

char detect_delim(const std::string& header) {
  // prefer tab; fall back to comma. Matches TSV (pheno) and CSV (cov_input).
  return (header.find('\t') != std::string::npos) ? '\t' : ',';
}

std::vector<std::string> read_fam_iids(const std::string& path) {
  std::ifstream f(path);
  if (!f) throw std::runtime_error("open " + path);
  std::vector<std::string> out;
  std::string line;
  while (std::getline(f, line)) {
    // FAM columns: FID IID PID MID SEX PHENO (space-delimited)
    std::istringstream is(line);
    std::string fid, iid;
    if (!(is >> fid >> iid)) continue;
    out.push_back(iid);
  }
  return out;
}

std::vector<std::string> read_pheno_iids(const std::string& path,
                                         const std::string& iid_col) {
  std::ifstream f(path);
  if (!f) throw std::runtime_error("open " + path);
  std::string hdr;
  if (!std::getline(f, hdr))
    throw std::runtime_error("empty pheno " + path);
  const char delim = detect_delim(hdr);
  auto cols = split_delim(hdr, delim);
  int idx = -1;
  for (size_t i = 0; i < cols.size(); ++i)
    if (cols[i] == iid_col) { idx = int(i); break; }
  if (idx < 0)
    throw std::runtime_error("input missing column '" + iid_col + "' (delim='" +
                             std::string(1, delim) + "')");
  std::vector<std::string> out;
  std::string line;
  while (std::getline(f, line)) {
    auto row = split_delim(line, delim);
    if (int(row.size()) <= idx) continue;
    out.push_back(row[idx]);
  }
  return out;
}

std::vector<RefLine> parse_ref_log(const std::string& log_path, int n_want) {
  std::ifstream f(log_path);
  if (!f) throw std::runtime_error("open " + log_path);
  std::regex re(R"(^Marker\s+(\d+):\s+freq=([-0-9.eE+]+),\s+maf=([-0-9.eE+]+),\s+missRate=([-0-9.eE+]+),\s+passQC=([01])\s*$)");
  std::string line;
  std::vector<RefLine> out;
  while (std::getline(f, line)) {
    std::smatch m;
    if (!std::regex_match(line, m, re)) continue;
    RefLine r;
    r.marker   = std::stoi(m[1]);
    r.freq     = std::stof(m[2]);
    r.maf      = std::stof(m[3]);
    r.missRate = std::stof(m[4]);
    r.passQC   = (m[5] == "1");
    if (r.marker < n_want) out.push_back(r);
  }
  std::sort(out.begin(), out.end(),
            [](const RefLine& a, const RefLine& b) { return a.marker < b.marker; });
  out.erase(std::unique(out.begin(), out.end(),
            [](const RefLine& a, const RefLine& b) { return a.marker == b.marker; }),
            out.end());
  return out;
}

bool approx_eq(float a, float b, float rel = 1e-4f, float abs_ = 1e-6f) {
  const float d = std::fabs(a - b);
  return d <= abs_ || d <= rel * std::max(std::fabs(a), std::fabs(b));
}

} // namespace

int main(int argc, char** argv) {
  if (argc < 6) {
    std::fprintf(stderr,
      "usage: %s <bed> <fam> <pheno.tsv> <pheno_iid_col> <stdout.log> "
      "[n_markers=20] [minMAF=0.01] [maxMiss=0.15]\n",
      argv[0]);
    return 2;
  }
  const std::string bed_path   = argv[1];
  const std::string fam_path   = argv[2];
  const std::string pheno_path = argv[3];
  const std::string iid_col    = argv[4];
  const std::string log_path   = argv[5];
  const int   n_markers = (argc > 6) ? std::atoi(argv[6]) : 20;
  const float min_maf   = (argc > 7) ? std::atof(argv[7]) : 0.01f;
  const float max_miss  = (argc > 8) ? std::atof(argv[8]) : 0.15f;

  try {
    std::fprintf(stderr, "[1/4] parsing inputs...\n");
    auto fam_iids   = read_fam_iids(fam_path);
    auto pheno_iids = read_pheno_iids(pheno_path, iid_col);
    const std::size_t N = fam_iids.size();
    std::fprintf(stderr, "  FAM  : N=%zu\n", N);
    std::fprintf(stderr, "  pheno: %zu rows on column '%s'\n",
                 pheno_iids.size(), iid_col.c_str());

    // FAM index lookup.
    std::unordered_map<std::string, int> fam_pos;
    fam_pos.reserve(N * 2);
    for (std::size_t i = 0; i < N; ++i) fam_pos.emplace(fam_iids[i], int(i) + 1);

    // Build indicator and collect FAM-ascending ptrsub.
    std::vector<bool> indicator(N, false);
    for (const auto& iid : pheno_iids) {
      auto it = fam_pos.find(iid);
      if (it != fam_pos.end()) indicator[it->second - 1] = true;
    }
    std::vector<int> ptrsub;
    ptrsub.reserve(pheno_iids.size());
    for (std::size_t i = 0; i < N; ++i)
      if (indicator[i]) ptrsub.push_back(int(i) + 1);
    const std::size_t Nnomissing = ptrsub.size();
    std::fprintf(stderr, "  Nnomissing = %zu (after FAM ∩ pheno, FAM-ascending)\n",
                 Nnomissing);

    std::fprintf(stderr, "[2/4] parsing reference stdout.log...\n");
    auto ref = parse_ref_log(log_path, n_markers);
    std::fprintf(stderr, "  %zu reference lines parsed\n", ref.size());

    std::fprintf(stderr, "[3/4] reading + decoding first %d markers...\n",
                 n_markers);
    saige::BedReaderPool reader(bed_path, N, /*n_threads=*/1);
    saige::BedLut lut;
    saige::build_bed_lookup(lut);

    const std::size_t nbyte_in  = reader.n_bytes_per_marker();
    const std::size_t nbyte_out = (Nnomissing + 3) / 4;

    std::vector<unsigned char> raw(nbyte_in);
    std::vector<unsigned char> packed(nbyte_out);

    saige::PackedFlat store;
    store.init(static_cast<std::size_t>(n_markers), nbyte_out);

    int mismatches = 0;
    int n_pass = 0;
    for (int i = 0; i < n_markers; ++i) {
      reader.read_marker(0, static_cast<std::size_t>(i), raw.data());
      saige::MarkerStats s{};
      saige::decode_marker(raw.data(), N, ptrsub.data(), Nnomissing,
                           min_maf, max_miss, lut, s, packed.data());
      if (s.passQC) {
        store.append(packed.data());
        ++n_pass;
      }

      // Find reference and diff.
      const RefLine* r = nullptr;
      for (const auto& x : ref) if (x.marker == i) { r = &x; break; }
      bool ok = true;
      std::string why;
      if (!r) {
        ok = false; why = "no ref line";
      } else {
        if (!approx_eq(r->freq, s.altFreq))      { ok = false; why += "freq "; }
        if (!approx_eq(r->maf, std::min(s.altFreq, 1.0f - s.altFreq))) {
          ok = false; why += "maf ";
        }
        if (!approx_eq(r->missRate, s.missingRate)) { ok = false; why += "missRate "; }
        if (r->passQC != s.passQC)               { ok = false; why += "passQC "; }
      }
      if (!ok) ++mismatches;

      std::printf("Marker %2d: freq=%.6g maf=%.6g missRate=%.6g mac=%d passQC=%d  %s",
                  i, s.altFreq, std::min(s.altFreq, 1.0f - s.altFreq),
                  s.missingRate, s.mac, int(s.passQC),
                  ok ? "[OK]" : ("[MISMATCH " + why + "]").c_str());
      if (r) std::printf("  ref: freq=%.6g maf=%.6g missRate=%.6g passQC=%d",
                         r->freq, r->maf, r->missRate, int(r->passQC));
      std::putchar('\n');
    }

    std::fprintf(stderr, "[4/4] summary:\n");
    std::fprintf(stderr, "  markers checked : %d\n", n_markers);
    std::fprintf(stderr, "  passed QC      : %d\n", n_pass);
    std::fprintf(stderr, "  store.n_stored : %zu\n", store.n_stored());
    std::fprintf(stderr, "  store.nbyte    : %zu / marker\n", store.nbyte());
    std::fprintf(stderr, "  mismatches vs saige-null log: %d\n", mismatches);

    if (mismatches) return 1;
    std::fprintf(stderr, "\nbed_pipeline_test: all %d markers match the saige-null reference\n",
                 n_markers);
    return 0;
  } catch (const std::exception& e) {
    std::fprintf(stderr, "bed_pipeline_test: %s\n", e.what());
    return 1;
  }
}
