// Generated by gen_erfc_consts.cpp from Boost 1.85 erf.hpp (53-bit erf_imp). Do not edit.
// Each value is (double)(decimal literal as long double), as BOOST_MATH_BIG_CONSTANT does.
#pragma once
static __device__ __constant__ double ERF_C_SMALL = 0x1.baea08536da23p-9;
static __device__ __constant__ double ERF_Y1 = 0x1.0b81cp+0;
static __device__ __constant__ double ERF_Y2 = 0x1.9fadap-2;
static __device__ __constant__ double ERF_Y3 = 0x1.0371ep-1;
static __device__ __constant__ double ERF_Y4 = 0x1.14c64p-1;
static __device__ __constant__ double ERF_Y5 = 0x1.1da64p-1;
static __device__ __constant__ double ERF_Z_ERF_LIMIT = 0x1.7b851ep+2;   // (double)5.93f
static __device__ __constant__ double ERF_P1[5] = {0x1.55bb50429b6dp-4, -0x1.5a47f6049a01ep-2, -0x1.a1c8cf1be61e7p-5, -0x1.fa6f563ab4349p-8, -0x1.5275a10372cd4p-12};
static __device__ __constant__ double ERF_Q1[5] = {0x1p+0, 0x1.d1ec93c6014b3p-2, 0x1.667dbdc6ee008p-4, 0x1.19563bb281b53p-7, 0x1.84eabadac6fep-12};
static __device__ __constant__ double ERF_P2[6] = {-0x1.91c770d9d3c38p-4, 0x1.6cc761c5cdfdp-3, 0x1.872cf216e5f4bp-3, 0x1.6c17f596974e1p-4, 0x1.3f917b098b969p-6, 0x1.d8f8dba7bf515p-10};
static __device__ __constant__ double ERF_Q2[7] = {0x1p+0, 0x1.d8fbb46b1d05ep+0, 0x1.6d20b0730d505p+0, 0x1.27f68988b9f55p-1, 0x1.fb4b28dd2f601p-4, 0x1.738a6d80ccf03p-7, 0x1.c5000f148a68ep-19};
static __device__ __constant__ double ERF_P3[6] = {-0x1.8ef3808bfbe3ap-6, 0x1.3ca7645df54c9p-5, 0x1.680608a766075p-5, 0x1.1fd54bd6a6244p-6, 0x1.a89fbecd94db8p-9, 0x1.ee97293c42ffbp-13};
static __device__ __constant__ double ERF_Q3[6] = {0x1p+0, 0x1.8a37ddbaa96dp+0, 0x1.f6fd9e749acf5p-1, 0x1.4d8cee8caf21ap-2, 0x1.cdf6fb1d81fe3p-5, 0x1.0cf09d7005348p-8};
static __device__ __constant__ double ERF_P4[6] = {0x1.83066cd0bf15ap-9, 0x1.c22e68cf6b2c5p-7, 0x1.13840e0e2140cp-7, 0x1.16f46da1af76bp-9, 0x1.066d54ccd32a6p-12, 0x1.7be0b780f7e4fp-17};
static __device__ __constant__ double ERF_Q4[6] = {0x1p+0, 0x1.0acc2fcb1378bp+0, 0x1.c538522309af5p-2, 0x1.88993f34aac72p-4, 0x1.5b48e7dd47e9bp-7, 0x1.f6b2fb953735bp-12};
static __device__ __constant__ double ERF_P5[7] = {0x1.9b9a82141fdacp-8, 0x1.1f5bd4085c48dp-6, -0x1.b383063c1348dp-3, -0x1.601c882adf2bfp-1, -0x1.46a330b7811e1p+1, -0x1.9d17fc9bea3fbp+1, -0x1.68a52784ed044p+1};
static __device__ __constant__ double ERF_Q5[7] = {0x1p+0, 0x1.65732e0a1496p+1, 0x1.61d0ae6a5ca5ep+3, 0x1.fdc7da2dc1122p+3, 0x1.6efce09ed825p+4, 0x1.b0349176f08c7p+3, 0x1.5efb5c445a48fp+2};
