// gen_erfc_consts.cpp -- emit erfc_boost53_consts.hpp: the rational-
// approximation coefficients of Boost.Math's 53-bit erf_imp (boost/math/
// special_functions/erf.hpp, Boost 1.85, Boost Software License 1.0) as
// hex-float double literals.
//
// Why a generator: BOOST_MATH_BIG_CONSTANT(T, 53, x) turns the decimal literal
// into a long double first and then casts to double. On x86-64 that is a
// double rounding (64-bit mantissa, then 53), which can differ in the last
// bit from a compiler reading the same decimal straight into a double. The
// device code must hold the very doubles the CPU's Boost holds, so they are
// produced here by the same two-step conversion on the same host and written
// out exactly (%a).
//
//   g++ -std=c++17 gen_erfc_consts.cpp -o gen_erfc_consts && ./gen_erfc_consts > erfc_boost53_consts.hpp
#include <cstdio>

#define C(x) ((double)(x##L))

static void arr(const char* name, const double* v, int n)
{
    std::printf("static __device__ __constant__ double %s[%d] = {", name, n);
    for (int i = 0; i < n; ++i) std::printf("%s%a", i ? ", " : "", v[i]);
    std::printf("};\n");
}

int main()
{
    // z < 0.5, z >= 1e-10: erf(z) = z * (Y + P(z^2) / Q(z^2))
    const double P1[] = { C(0.0834305892146531832907), C(-0.338165134459360935041), C(-0.0509990735146777432841),
                          C(-0.00772758345802133288487), C(-0.000322780120964605683831) };
    const double Q1[] = { C(1.0), C(0.455004033050794024546), C(0.0875222600142252549554),
                          C(0.00858571925074406212772), C(0.000370900071787748000569) };
    // 0.5 <= z < 1.5: erfc(z) = (Y + P(z-0.5) / Q(z-0.5)) * exp(-z^2) / z
    const double P2[] = { C(-0.098090592216281240205), C(0.178114665841120341155), C(0.191003695796775433986),
                          C(0.0888900368967884466578), C(0.0195049001251218801359), C(0.00180424538297014223957) };
    const double Q2[] = { C(1.0), C(1.84759070983002217845), C(1.42628004845511324508), C(0.578052804889902404909),
                          C(0.12385097467900864233), C(0.0113385233577001411017), C(0.337511472483094676155e-5) };
    // 1.5 <= z < 2.5
    const double P3[] = { C(-0.0243500476207698441272), C(0.0386540375035707201728), C(0.04394818964209516296),
                          C(0.0175679436311802092299), C(0.00323962406290842133584), C(0.000235839115596880717416) };
    const double Q3[] = { C(1.0), C(1.53991494948552447182), C(0.982403709157920235114), C(0.325732924782444448493),
                          C(0.0563921837420478160373), C(0.00410369723978904575884) };
    // 2.5 <= z < 4.5
    const double P4[] = { C(0.00295276716530971662634), C(0.0137384425896355332126), C(0.00840807615555585383007),
                          C(0.00212825620914618649141), C(0.000250269961544794627958), C(0.113212406648847561139e-4) };
    const double Q4[] = { C(1.0), C(1.04217814166938418171), C(0.442597659481563127003), C(0.0958492726301061423444),
                          C(0.0105982906484876531489), C(0.000479411269521714493907) };
    // 4.5 <= z < 28: argument 1/z
    const double P5[] = { C(0.00628057170626964891937), C(0.0175389834052493308818), C(-0.212652252872804219852),
                          C(-0.687717681153649930619), C(-2.5518551727311523996), C(-3.22729451764143718517),
                          C(-2.8175401114513378771) };
    const double Q5[] = { C(1.0), C(2.79257750980575282228), C(11.0567237927800161565), C(15.930646027911794143),
                          C(22.9367376522880577224), C(13.5064170191802889145), C(5.48409182238641741584) };

    std::printf("// Generated by gen_erfc_consts.cpp from Boost 1.85 erf.hpp (53-bit erf_imp). Do not edit.\n");
    std::printf("// Each value is (double)(decimal literal as long double), as BOOST_MATH_BIG_CONSTANT does.\n");
    std::printf("#pragma once\n");
    std::printf("static __device__ __constant__ double ERF_C_SMALL = %a;\n", C(0.003379167095512573896158903121545171688));
    std::printf("static __device__ __constant__ double ERF_Y1 = %a;\n", (double)1.044948577880859375f);
    std::printf("static __device__ __constant__ double ERF_Y2 = %a;\n", (double)0.405935764312744140625f);
    std::printf("static __device__ __constant__ double ERF_Y3 = %a;\n", (double)0.50672817230224609375f);
    std::printf("static __device__ __constant__ double ERF_Y4 = %a;\n", (double)0.5405750274658203125f);
    std::printf("static __device__ __constant__ double ERF_Y5 = %a;\n", (double)0.5579090118408203125f);
    std::printf("static __device__ __constant__ double ERF_Z_ERF_LIMIT = %a;   // (double)5.93f\n", (double)5.93f);
    arr("ERF_P1", P1, 5); arr("ERF_Q1", Q1, 5);
    arr("ERF_P2", P2, 6); arr("ERF_Q2", Q2, 7);
    arr("ERF_P3", P3, 6); arr("ERF_Q3", Q3, 6);
    arr("ERF_P4", P4, 6); arr("ERF_Q4", Q4, 6);
    arr("ERF_P5", P5, 7); arr("ERF_Q5", Q5, 7);
    return 0;
}
