#!/usr/bin/env python3
"""gen_glibc_tables.py [out.cuh] -- write gpu_er_glibc_tables.cuh for gpu/gpu_er.cu.

Reads the constants of glibc's exp and log (__exp_data, __log_data, plus the few
literal constants the FMA variants load) straight out of the libm the CPU build
links, so the device port of __exp_fma / __log_fma (gpu_er_glibc.cuh) uses the
same bits. The addresses are those of Ubuntu 22.04's libm.so.6 from glibc
2.35-0ubuntu3.15 (md5 below; found by disassembling the ifunc targets of exp and
log, see S2_ER_GPU.md). A different libm needs the addresses found again: the
script refuses to run on one.
"""
import hashlib
import subprocess, struct, re, sys
L="/usr/lib/x86_64-linux-gnu/libm.so.6"
LIBM_MD5="2b2932970a9db227d69131ad510e6ad5"
assert hashlib.md5(open(L,"rb").read()).hexdigest()==LIBM_MD5, "libm differs from the one the addresses were read from"
def dump(a, n):
    out = subprocess.run(["objdump","-s","--start-address=%#x"%a,"--stop-address=%#x"%(a+n),L],capture_output=True,text=True).stdout
    b = bytearray()
    for line in out.splitlines():
        m = re.match(r"^\s*([0-9a-f]+)\s((?:[0-9a-f]{2,8}\s){1,4})", line)
        if not m: continue
        addr = int(m.group(1),16)
        hexs = "".join(m.group(2).split())
        if addr < a or addr >= a+n: continue
        b += bytes.fromhex(hexs)
    assert len(b) >= n, (len(b), n)
    return bytes(b[:n])
def u64s(b): return struct.unpack("<%dQ"%(len(b)//8), b)
E = dump(0xaf960, 0x70 + 256*8)
Ev = u64s(E)
G = dump(0xb01e0, 0x90 + 128*16)
Gv = u64s(G)
misc = {}
for name,a in [("one",0x8a2d0),("p1022",0x93050),("p2_1009",0x96630),("negone",0x969b0),("two27",0x930c8),("two52",0x8a2f0)]:
    misc[name] = u64s(dump(a,8))[0]
def f(u): return struct.unpack("<d", struct.pack("<Q",u))[0]
o = []
o.append("// Generated by er_tools/gen_glibc_tables.py from %s (Ubuntu glibc 2.35-0ubuntu3.15): the constant"%L)
o.append("// tables of __exp_data / __log_data read out of the very library the CPU build")
o.append("// calls, so the device port uses bit-identical constants. Do not edit by hand.")
o.append("#pragma once\n#include <cstdint>")
names = ["invln2N","shift","negln2hiN","negln2loN","C2","C3","C4","C5"]
for i,nm in enumerate(names):
    o.append("#define GLX_EXP_%s 0x%016xULL  /* %r */" % (nm, Ev[i], f(Ev[i])))
o.append("__device__ __constant__ uint64_t glx_exp_tab[256] = {")
tab = Ev[14:14+256]
for i in range(0,256,4): o.append("  " + ", ".join("0x%016xULL"%x for x in tab[i:i+4]) + ",")
o.append("};")
lnames = ["ln2hi","ln2lo"] + ["A%d"%i for i in range(5)] + ["B%d"%i for i in range(11)]
for i,nm in enumerate(lnames):
    o.append("#define GLX_LOG_%s 0x%016xULL  /* %r */" % (nm, Gv[i], f(Gv[i])))
o.append("__device__ __constant__ uint64_t glx_log_tab[256] = {  /* invc, logc pairs */")
lt = Gv[18:18+256]
for i in range(0,256,4): o.append("  " + ", ".join("0x%016xULL"%x for x in lt[i:i+4]) + ",")
o.append("};")
for k,v in misc.items(): o.append("#define GLX_K_%s 0x%016xULL  /* %r */" % (k, v, f(v)))
open(sys.argv[1] if len(sys.argv) > 1 else "gpu_er_glibc_tables.cuh","w").write("\n".join(o)+"\n")
print("\n".join(l for l in o if l.startswith("#define")))
